### ISSUE TITLE
Running in console causes NPE

### ISSUE THREAD

**Issue by eed3si9n** [eed3si9n/expecty#30]
## steps

```scala
scala> import com.eed3si9n.expecty.Expecty.assert
import com.eed3si9n.expecty.Expecty.assert

scala> assert("1" == 1)
```

## problem

```scala
scala> import com.eed3si9n.expecty.Expecty.assert
import com.eed3si9n.expecty.Expecty.assert

scala> assert("1" == 1)
             ^
       error: exception during macro expansion:
       java.lang.RuntimeException: Expecty: Error rewriting expression.
       Text: assert("1" == 1)
       AST : Apply(Select(Literal(Constant("1")), TermName("$eq$eq")), List(Literal(Constant(1))))
       	at com.eed3si9n.expecty.RecorderMacro.recordExpressions(RecorderMacro.scala:59)
       	at com.eed3si9n.expecty.RecorderMacro.apply(RecorderMacro.scala:25)
       	at com.eed3si9n.expecty.RecorderMacro1$.apply(RecorderMacro.scala:176)
       Caused by: java.lang.NullPointerException
       	at com.eed3si9n.expecty.RecorderMacro.getSourceLocation(RecorderMacro.scala:158)
       	at com.eed3si9n.expecty.RecorderMacro.recordExpression(RecorderMacro.scala:102)
       	at com.eed3si9n.expecty.RecorderMacro.recordExpressions(RecorderMacro.scala:56)
       	at com.eed3si9n.expecty.RecorderMacro.apply(RecorderMacro.scala:25)
       	at com.eed3si9n.expecty.RecorderMacro1$.apply(RecorderMacro.scala:176)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:498)
       	at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers.$anonfun$resolveJavaReflectionRuntime$6(JavaReflectionRuntimes.scala:51)
       	at scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime(Macros.scala:758)
       	at scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime$(Macros.scala:734)
       	at scala.tools.nsc.Global$$anon$6.macroExpandWithRuntime(Global.scala:485)
       	at scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:564)
       	at scala.tools.nsc.Global.withInfoLevel(Global.scala:228)
       	at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:557)
       	at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:544)
       	at scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:719)
       	at scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:717)
       	at scala.tools.nsc.Global$$anon$6.standardMacroExpand(Global.scala:485)
       	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$10.default(AnalyzerPlugins.scala:456)
       	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$10.default(AnalyzerPlugins.scala:453)
       	at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:410)
       	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:453)
       	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:453)
       	at scala.tools.nsc.Global$$anon$6.pluginsMacroExpand(Global.scala:485)
       	at scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:708)
       	at scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:701)
       	at scala.tools.nsc.Global$$anon$6.macroExpand(Global.scala:485)
       	at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1217)
       	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1285)
       	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5988)
       	at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:6062)
       	at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1128)
       	at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1740)
       	at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1914)
       	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1878)
       	at scala.tools.nsc.typechecker.Namers$Namer$ValTypeCompleter.completeImpl(Namers.scala:945)
       	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2062)
       	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2060)
       	at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2055)
       	at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1546)
       	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1518)
       	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1707)
       	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5573)
       	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5973)
       	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6051)
       	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3397)
       	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3397)
       	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2058)
       	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1889)
       	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5882)
       	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5973)
       	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6051)
       	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3397)
       	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3397)
       	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2058)
       	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1889)
       	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5882)
       	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5973)
       	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6051)
       	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3397)
       	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3397)
       	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5582)
       	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5885)
       	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5973)
       	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:117)
       	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
       	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:105)
       	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1515)
       	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1499)
       	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:741)
       	at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:953)
       	at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:533)
       	at scala.tools.nsc.interpreter.IMain.doInterpret(IMain.scala:519)
       	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:503)
       	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:501)
       	at scala.tools.nsc.interpreter.shell.ILoop.loop$1(ILoop.scala:878)
       	at scala.tools.nsc.interpreter.shell.ILoop.interpretStartingWith(ILoop.scala:906)
       	at scala.tools.nsc.interpreter.shell.ILoop.command(ILoop.scala:433)
       	at scala.tools.nsc.interpreter.shell.ILoop.processLine(ILoop.scala:440)
       	at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:458)
       	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:968)
       	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:78)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:498)
       	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
       	at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:210)
       	at sbt.Console.console0$1(Console.scala:48)
       	at sbt.Console.$anonfun$apply$2(Console.scala:51)
       	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
       	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
       	at sbt.TrapExit$App.run(TrapExit.scala:257)
       	at java.lang.Thread.run(Thread.java:748)
```

/cc @Baccata

**Comment by Baccata** [comment]
Oh, my bad, I'll have a fix today
