### ISSUE TITLE
vararg expect doesn't show the values

### ISSUE THREAD

**Issue by eed3si9n** [eed3si9n/expecty#32]
## steps

```scala
scala> import com.eed3si9n.expecty.Expecty.expect
import com.eed3si9n.expecty.Expecty.expect

scala> expect(1 == 2, "foo" == 2, "bar" == 1)
```

## problem

```scala
scala> import com.eed3si9n.expecty.Expecty.expect
import com.eed3si9n.expecty.Expecty.expect

scala> expect(1 == 2, "foo" == 2, "bar" == 1)
java.lang.AssertionError: assertion failed

expect(1 == 2, "foo" == 2, "bar" == 1)


  at com.eed3si9n.expecty.ExpectyBase$ExpectyListener.expressionRecorded(Expecty.scala:38)
  at com.eed3si9n.expecty.RecorderRuntime.recordExpression(RecorderRuntime.scala:39)
  ... 36 elided
```

It doesn't show the value breakdown like `assert(...)` does.

## expectation

It shows the value breakdown like `assert(...)`.

**Comment by eed3si9n** [comment]
@Baccata Is this intentional?

**Comment by Baccata** [comment]
@eed3si9n as far as I know, the behaviour of "assert" when all values are literal (ie literal strings, booleans or numbers) is to not breakdown the expression, that was already the case and "expect" follows that. 

``` 
java.lang.AssertionError: assertion failed

assert(1 == 2)


  at com.eed3si9n.expecty.ExpectyBase$ExpectyListener.expressionRecorded(Expecty.scala:38)
  at com.eed3si9n.expecty.RecorderRuntime.recordExpression(RecorderRuntime.scala:39)
  ... 40 elided
```

When references are involved however, you get the expected behaviour : 

``` 
scala> val x = 1 
val x: Int = 1

scala> expect(x == 1, x == 2, x == 3)
java.lang.AssertionError: assertion failed

expect(x == 1, x == 2, x == 3)
               | |
               1 false

  at com.eed3si9n.expecty.ExpectyBase$ExpectyListener.expressionRecorded(Expecty.scala:38)
  at com.eed3si9n.expecty.RecorderRuntime.recordExpression(RecorderRuntime.scala:39)
  ... 40 elided
```

**That being said**, I haven't changed the behaviour expecty's listener to aggregate errors before throwing, and in the example above, you'll only see the breakdown of the first expression that failed.

**Comment by Baccata** [comment]
To address that last point : https://github.com/eed3si9n/expecty/pull/33
